import { useState } from "react";
import fortcyLogo from "../assets/fortcy-logo.png";

function ProfileSetupScreen({ onComplete }: { onComplete: (name: string) => void }) {
  const [name, setName] = useState("");
  const submit = () => { const value = name.trim(); if (value) onComplete(value); };
  return <div style={{ width: "100vw", height: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "radial-gradient(circle at 50% 20%, rgba(38,83,190,.3), transparent 42%), #020712", color: "#fff", fontFamily: '"Segoe UI", Arial, sans-serif' }}><div style={{ width: "420px", maxWidth: "90vw", padding: "34px", textAlign: "center", background: "linear-gradient(145deg, rgba(10,26,52,.98), rgba(4,10,22,.99))", border: "1px solid rgba(0,229,255,.35)", borderRadius: "18px" }}><img src={fortcyLogo} alt="Fortcy" style={{ width: "210px", maxWidth: "80%" }} /><div style={{ color: "#00e5ff", fontSize: "11px", fontWeight: 900, letterSpacing: "1.6px", marginTop: "16px" }}>PLAYER PROFILE SETUP</div><h1 style={{ margin: "10px 0 8px", fontSize: "27px" }}>Enter your Fortnite username</h1><p style={{ color: "#91a3c2", fontSize: "13px", lineHeight: 1.5 }}>Use your Epic display name to load your profile. Fortcy does not inject into Fortnite or read credentials.</p><input autoFocus value={name} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") submit(); }} placeholder="Epic display name" aria-label="Epic display name" style={{ width: "100%", boxSizing: "border-box", padding: "13px 14px", color: "#fff", background: "#061326", border: "1px solid rgba(74,117,184,.7)", borderRadius: "9px" }} /><button type="button" onClick={submit} disabled={!name.trim()} style={{ width: "100%", marginTop: "14px", padding: "13px", color: "#001018", fontWeight: 900, background: name.trim() ? "#00e5ff" : "#3d6873", border: 0, borderRadius: "9px" }}>Continue to dashboard</button></div></div>;
}
export default ProfileSetupScreen;
